// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/giovane-aG/goexpert/9-APIs/internal/infra/database"
	"gorm.io/gorm"
)

import (
	_ "github.com/giovane-aG/goexpert/9-APIs/docs"
)

// Injectors from wire.go:

func InitializeUserDatabase(db2 *gorm.DB) *database.User {
	user := database.NewUser(db2)
	return user
}
