// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/giovane-aG/goexpert/9-APIs/internal/infra/database"
	"github.com/giovane-aG/goexpert/9-APIs/internal/infra/http/user"
)

// Injectors from wire.go:

func NewUserController(user database.User) *user_controller.UserController {
	userController := user_controller.NewUserController(user)
	return userController
}
