basePath: /
definitions:
  dtos.CreateUserDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  user_controller.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: giovaneaalmeida27@gmail.com
    name: Giovane Aguiar
  description: Production API authentication.
  termsOfService: http://swagger.io/terms/
  title: Go Expert API
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateUserDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user_controller.Error'
      summary: Create new user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
